Fixed incomplete error message
yugabyte/cqlsh pull request #23
Opened 2024-01-31 09:15 UTC by swapshivam3

Using python2 was showing incomplete error messages as the err.message field is empty. Added a check to skip that if it is empty.

2024-02-06 07:53 UTC, HarshDaryani896 approved these changes

2024-02-07 11:12 UTC, d-uspenskiy requested changes
This change doesn't look like valid fix because of the following:
- there are multiple occurrence of same pattern in the code 
- in python2.7 the `message` field return empty string because multiple arguments was passed to exception's object constructor
- the `message` field is deprecated since 2.6. In case YB is not interested in supporting python prior to 2.7 `str(err)` must be used instead of `message` field. In other case it seems reasonable to create helper function and use it everywhere

2024-02-13 12:07 UTC, HarshDaryani896 requested changes
Thank you @d-uspenskiy for pointing this out. We should cover all the occurrences of this pattern in the code.

@swapshivam3  I see a couple of other occurrences of the same pattern in the code. Please verify the same and implement the fix for all occurences.

2024-04-01 12:13 UTC, HarshDaryani896 commented
Created a new PR for this: #24

2024-04-01 12:13 UTC, closed without merging